services:
  franken:
    container_name: franken
    build: .
    restart: always
    volumes:
      - ./app:/app
      - ./custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    tty: true

  mariadb:
    container_name: mariadb
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: labnotes
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    ports:
      - "81:80"
    environment:
      PMA_ARBITRARY: 1

volumes:
  db_data: